// <auto-generated />
using DataManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataManager.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200517125121_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("DataManager.Models.Subscribers", b =>
                {
                    b.Property<long>("chatID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("wantsDlcInfo")
                        .HasColumnType("INTEGER");

                    b.HasKey("chatID");

                    b.ToTable("subscribers");
                });
#pragma warning restore 612, 618
        }
    }
}
